sudo: required
services:
  - docker

before_install:
  - docker build -t nreoch9/nextjs-graphql-hooks-auth-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nreoch9/nextjs-graphql-hooks-auth-client-test yarn test -- --coverage

after_success:
  # Build images
  - docker build -t nreoch9/nextjs-graphql-hooks-auth-client:latest ./client
  # - docker build -t nreoch9/nextjs-graphql-hooks-auth-nginx:latest ./nginx
  - docker build -t nreoch9/nextjs-graphql-hooks-auth-server:latest ./server
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push nreoch9/nextjs-graphql-hooks-auth-client:latest
  # - docker push nreoch9/nextjs-graphql-hooks-auth-nginx:latest
  - docker push nreoch9/nextjs-graphql-hooks-auth-server:latest
