apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: nreoch9/nextjs-graphql-hooks-auth-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://database:27017/nextjs-graphql-hooks-auth"
            - name: CLIENT_URI
              value: "http://192.168.55.143"
            - name: PORT
              value: "8000"
            - name: MAIL_HOST
              value: "smtp.mailtrap.io"
            - name: MAIL_PORT
              value: "2525"
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: mailuser
                  key: MAIL_USER
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: mailpass
                  key: MAIL_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWT_SECRET
